spin_manifest_version = "1"
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""
name = "sentiment-analysis-py"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "sentiment-analysis-py"
source = "app.wasm"
ai_models = ["llama2-chat"]
[component.trigger]
route = "/..."
[component.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "Pipfile"]
